inherit_gem:
  govuk-lint: configs/rubocop/all.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/environments/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  # Disable block length restriction for files that use a DSL around blocks.
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'

RSpec/ContextWording:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - e
    - to

Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

# It's better to be explicit about the class that's being tested
RSpec/DescribedClass:
  Enabled: false

# This cop wants us to use `expect().to change(Candidate, :count)` instead
# of `expect().to change { Candidate.count }`, which doesn't seem better.
RSpec/ExpectChange:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

# In acceptance tests it's often handy to user instance variables to keep track of state 
RSpec/InstanceVariable:
  Enabled: false
