trigger:
  batch: true
  paths:
    include:
      - Dockerfile
      - Gemfile
      - Gemfile.lock
      - package.json
      - yarn.lock

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerHubUsername: dfedigital
  gemsNodeModulesImageName: 'apply-for-teacher-training-gems-node-modules'
  
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '19.03.9'

- bash: |
    GEM_NODE_PACKAGE_FILES_SHA=$(sha1sum Gemfile Gemfile.lock Dockerfile package.json yarn.lock)
    echo $GEM_NODE_PACKAGE_FILES_SHA
    DEPENDENCIES_SHA=$(echo $GEM_NODE_PACKAGE_FILES_SHA | sha1sum | cut -c 1-7)
    echo "##vso[task.setvariable variable=DEPENDENCIES_SHA]$DEPENDENCIES_SHA"
    echo "##[command]$DEPENDENCIES_SHA"
  displayName: Prepare environment variables

- bash: |
    set -eux
    echo "gemsNodeModulesImageName is $(gemsNodeModulesImageName)"
    docker build \
    --target $(gemsNodeModulesImageName) \
    -t $(dockerHubUsername)/$(gemsNodeModulesImageName):$(DEPENDENCIES_SHA) \
    "."
  displayName: Build ${{ variables.dockerHubUsername }}/${{ variables.gemsNodeModulesImageName }}

- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: 'DfE Docker Hub'
    command: 'login'

- bash: |
    set -eux
    docker images
    docker push $(dockerHubUsername)/$(gemsNodeModulesImageName):$(DEPENDENCIES_SHA)
  displayName: Docker Push ${{ variables.dockerHubUsername }}/${{ variables.gemsNodeModulesImageName }}

- task: Docker@2
  displayName: Docker Logout
  inputs:
    containerRegistry: 'DfE Docker Hub'
    command: 'logout'
