version: '3.6'
services:
  web:
    image: ${dockerHubUsername}/${dockerHubImageName}:latest
    environment:
      - RAILS_ENV
      - DEFAULT_PROVIDER_EMAIL
      - GOVUK_NOTIFY_API_KEY
      - SECRET_KEY_BASE=${railsSecretKeyBase}
      - DOMAIN=${domain}
