# used to mount the local dev folder as the containers workdir for development
version: "3.6"
services:
  web:
    volumes:
      - ${APP_ROOT_FOLDER:-.}:/app
    environment:
      - RAILS_ENV=development
      - AUTHORISED_HOSTS=localhost
