version: '3.6'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=developmentpassword
  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - DB_DATABASE=bat_apply_dev
      - DB_PORT=5432
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
volumes:
  db_data:
  node_modules:
