version: "3.6"
services:
  web:
    build:
      target: prod-build
      args:
        bundleWithout: 'development'
    image: ${dockerHubUsername}/${dockerHubImageName}:latest
    environment:
      - RAILS_ENV
      - GOVUK_NOTIFY_API_KEY
      - SECRET_KEY_BASE=${railsSecretKeyBase}
      - DOMAIN
      - STAGING_DOMAIN
      - SENTRY_DSN
