version: '3.6'
volumes:
  dbdata:
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    image: ${dockerHubUsername}/${dockerHubImageName}:latest
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
