version: "3.2"
volumes:
  node_modules:

services:
  db:
    image: postgres:11.1-alpine
  web:
    build:
      context: .
      cache_from:
        - govukdfe/apply-for-postgraduate-teacher-training:latest
    image: govukdfe/apply-for-postgraduate-teacher-training:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - "node_modules:/app/node_modules"
    depends_on:
      - "db"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:setup && bundle exec rails server -p 3000 -b '0.0.0.0'"
    environment:
      - APPLY_DATABASE_HOST=db
      - APPLY_DATABASE_USERNAME=postgres
