trigger:
    batch: true
    branches:
      include:
        - '*'
pr: none

variables:
  System.Debug: false

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo $BRANCH_NAME
    env:
      BRANCH_NAME: $(Build.SourceBranchName)
  - script: |
      echo "New step"
    displayName: New Step
  
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: drop
      PathtoPublish: $(System.DefaultWorkingDirectory)
    