development: &default
  codes:
    - 1HQ  # Alliance of Leading Learning
    - 24L  # Ashton on Mersey SCITT
    - 1N1  # Gorse SCITT
    - 254  # Nottinghamshire Torch SCITT
    - 2LR  # Oriel High School
    - R55  # Royal Academy of Dance
    - L06  # Shotton Hall SCITT
    - S31  # Somerset SCITT Consortium
    - 12K  # Trent Valley Teaching School Alliance
    - D87  # Durham SCITT
    - N83  # North West Shares SCITT
    - 1OT  # The Academy at Shotton Hall
    - N83  # North West Shares SCITT
    - 2B2  # Yorkshire and Humber Teacher Training
    - 255  # Northern Lights SCITT
    - 2ET  # Prince Henry's High School & South Worcestershire SCITT
    - T25  # Essex and Thames Primary SCITT
    - 1OS  # Essex School Direct
    - S17  # SCITTELS
    - C76  # Colchester Teacher Training Consortium
    - 2DB  # Colchester Teacher Training
    - M82  # Mid Essex Initial Teacher Training
    - 2B5  # Hillingdon SCITT
    - 2GU  # Claydon High School
    - 1ZN  # Thorpe St Andrew School

production:
  <<: *default
