name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variable
        run:  |
          GEM_NODE_MODULES_HASH=${{ hashFiles('Dockerfile', 'Gemfile', 'Gemfile.lock', 'package.json', 'yarn.lock') }}
          echo "GEM_NODE_MODULES_HASH=${GEM_NODE_MODULES_HASH}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=ghcr.io/dfe-digital/apply-teacher-training:paas-${{ github.sha }}" >> $GITHUB_ENV
          echo "GEMS_NODE_MODULES_IMAGE=ghcr.io/dfe-digital/apply-teacher-training-gems-node-modules:paas-${GEM_NODE_MODULES_HASH}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build gems-node-modules Docker Image
        uses: docker/build-push-action@v2
        with:
          target: apply-for-teacher-training-gems-node-modules
          tags: ${{ env.GEMS_NODE_MODULES_IMAGE }}
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-to: type=inline
          cache-from: type=registry,ref=${{ env.GEMS_NODE_MODULES_IMAGE }}
          build-args: VERSION=${{ github.sha }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.DOCKER_IMAGE}}
          push: true
          pull: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-to: type=inline
          cache-from: |
            type=registry,ref=${{ env.DOCKER_IMAGE }}
            type=registry,ref=${{ env.GEMS_NODE_MODULES_IMAGE }}
          build-args: |
            VERSION=${{ github.sha }}
            BASE_RUBY_IMAGE_WITH_GEMS_AND_NODE_MODULES=${{ env.GEMS_NODE_MODULES_IMAGE }}

  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    container: 
      image: ghcr.io/dfe-digital/apply-teacher-training:paas-${{ github.sha }}
      options: -a STDOUT -a STDERR -t
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
    steps:
    - run:  bundle exec rubocop --format clang --parallel
      name: Rubocop

    - run:  bundle exec rake erblint
      name: ERB Linter
    
    - run:  bundle exec rake brakeman
      name: Brakeman

  test:
    name: Tests
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests: [unit, integration]
        feature-flags: [on, off]
        include:
          - tests: unit
            include-pattern: spec/**/**/*_spec.rb
            exclude-pattern: spec/{system,requests}/**/*_spec.rb
          - tests: integration
            include-pattern: spec/{system,requests}/**/*_spec.rb            
            exclude-pattern: spec/**/**/*_spec.rb
    services:
      redis: 
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:11.10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    defaults:
      run:
        working-directory: /app
    container: 
      image: ghcr.io/dfe-digital/apply-teacher-training:paas-${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      env:
        RAILS_ENV: test
        DB_HOSTNAME: postgres
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        REDIS_URL: redis://redis:6379/0
        DB_PORT: 5432
    steps:
      - name: Setup Database
        run: bundle exec rake db:setup

      - name: ${{ matrix.tests }} tests with feature flags ${{ matrix.feature-flags }}
        run: bundle exec --verbose rspec --exclude-pattern ${EXCLUDE_PATTERN} --pattern ${INCLUDE_PATTERN} --format documentation
        env:
          INCLUDE_PATTERN: ${{ matrix.include-pattern }}
          EXCLUDE_PATTERN: ${{ matrix.exclude-pattern }}
          DEFAULT_FEATURE_FLAG_STATE: ${{ matrix.feature-flags }}
