name: Build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}

      - name: Set up gems-node-modules Docker Buildx
        id: buildx-gem-node-modules
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache gems-node-modules Docker layers
        id:   cache-gems-node-modules
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-gem-node-modules-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', 'Gemfile', 'Gemfile.lock', 'package.json', 'yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-buildx-gem-node-modules

      - name: Cache Docker layers
        id:   cache-docker-layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Set Environment Variable
        run:  |
          echo "DOCKER_IMAGE=ghcr.io/dfe-digital/apply-teacher-training:paas-${{ github.sha }}" >> $GITHUB_ENV
          echo "GEMS_NODE_MODULES_IMAGE=ghcr.io/dfe-digital/apply-teacher-training-gems-node-modules:paas-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build gems-node-modules Docker Image
        if: steps.cache-gems-node-modules.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          target: apply-for-teacher-training-gems-node-modules
          tags: ${{ env.GEMS_NODE_MODULES_IMAGE }}
          push: true
          builder: ${{ steps.buildx-gem-node-modules.outputs.name }}
          cache-to: type=local,dest=/tmp/.buildx-gem-node-modules-cache
          cache-from: type=local,src=/tmp/.buildx-gem-node-modules-cache
          build-args: VERSION=${{ github.sha }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.DOCKER_IMAGE}}
          push: true
          pull: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-to: type=local,dest=/tmp/.buildx-cache
          cache-from: type=local,src=/tmp/.buildx-cache
          build-args: | 
            VERSION=${{ github.sha }} 
            BASE_RUBY_IMAGE_WITH_GEMS_AND_NODE_MODULES=${{ env.GEMS_NODE_MODULES_IMAGE }}

  lint:
    name: lint
    needs: [build]
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/dfe-digital/apply-teacher-training:paas-${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
    steps:
    - run:  bundle exec rubocop --format clang --parallel
      name: Rubocop
